In [19]:
import pandas as pd
import numpy as np
def fixNumbers(data):
    data['Latitude'] = data['Latitude'].map(lambda x: x.replace(',', '.'))
    data['Longitude'] = data['Longitude'].map(lambda x: x.replace(',', '.'))
    #data['Profit'] = data['Profit'].map(lambda x: x.replace(',', '.'))
    #data['Profit'] = data['Profit'].astype(float)
    #data['Utility_rate'] = data['Utility_rate'].map(lambda x: x.replace(',', '.'))
    #data['Utility_rate'] = data['Utility_rate'].astype(float)

data = pd.read_csv('Arcata_Usage.csv', sep=',')
#fixNumbers(data)
#data[:3]
#data['Utility_rate']

#data.dtypes
#data.shape
dates = pd.date_range('1/1/2015', periods=365)
year_usage = pd.DataFrame(data['Electricity:Facility [kW](Hourly)'].reshape(24,365),index=np.arange(24),columns = dates)
mean_hourly_load = pd.DataFrame(year_usage.mean(axis=1),columns = ['usage'])
mean_hourly_load

       usage
0   1.044997
1   1.041240
2   1.016437
3   1.005543
4   0.929508
5   0.905714
6   0.883383
7   0.860496
8   0.856987
9   0.798704
10  0.753406
11  0.771289
12  0.752557
13  0.760657
14  0.722241
15  0.754815
16  0.807606
17  0.810778
18  0.890224
19  0.903971
20  0.936735
21  0.955408
22  1.047903
23  1.025364

In [20]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  

x = np.arange(23)
plt.plot(x, mean_hourly_load['usage'])
plt.title('Horuly Usage')
plt.show()

ImportError: No module named matplotlib